permalink: /:title
destination: ./.build

exclude: ['gulpfile.js', 'package.json', 'node_modules', 'docs', 'config.rb']

title: carlrafting.com

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-relative-links

whitelist:
  - jekyll-redirect-from
