[[headers]]
    for = "/*"
        [headers.values]
            X-Content-Type-Options = "nosniff"
            Content-Security-Policy = '''
                default-src 'self';
                style-src 'unsafe-inline';
                script-src 'unsafe-inline'
            '''
